# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualistation_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        devHeight = 1080
        devWidth = 1920
        userWidth = QtWidgets.QDesktopWidget().screenGeometry(-1).width()
        userHeight = QtWidgets.QDesktopWidget().screenGeometry(-1).height()
        heightSF = devHeight/userHeight
        widthSF = devWidth/userWidth
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(round(997*widthSF), round(heightSF*828))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, round(40*heightSF)))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, round(50*heightSF)))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.loadCsvPushButton = QtWidgets.QPushButton(self.frame_4)
        self.loadCsvPushButton.setObjectName("loadCsvPushButton")
        self.horizontalLayout_2.addWidget(self.loadCsvPushButton)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.simulationTab = QtWidgets.QWidget()
        self.simulationTab.setObjectName("simulationTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.simulationTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.simulationTab)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setMaximumSize(QtCore.QSize(round(300*widthSF), 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_14)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.runSpinBox = QtWidgets.QSpinBox(self.frame_14)
        self.runSpinBox.setMinimum(1)
        self.runSpinBox.setMaximum(1000000000)
        self.runSpinBox.setObjectName("runSpinBox")
        self.horizontalLayout_7.addWidget(self.runSpinBox)
        self.verticalLayout_16.addWidget(self.frame_14)
        self.frame_22 = QtWidgets.QFrame(self.frame_13)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.frame_22)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.daySpinBox = QtWidgets.QSpinBox(self.frame_22)
        self.daySpinBox.setMinimum(-1)
        self.daySpinBox.setMaximum(1000000000)
        self.daySpinBox.setProperty("value", -1)
        self.daySpinBox.setObjectName("daySpinBox")
        self.horizontalLayout_15.addWidget(self.daySpinBox)
        self.verticalLayout_16.addWidget(self.frame_22)
        self.frame_21 = QtWidgets.QFrame(self.frame_13)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.frame_21)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.balancedSpinBox = QtWidgets.QSpinBox(self.frame_21)
        self.balancedSpinBox.setObjectName("balancedSpinBox")
        self.horizontalLayout_14.addWidget(self.balancedSpinBox)
        self.verticalLayout_16.addWidget(self.frame_21)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.frame_16)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.idealistSpinBox = QtWidgets.QSpinBox(self.frame_16)
        self.idealistSpinBox.setObjectName("idealistSpinBox")
        self.horizontalLayout_9.addWidget(self.idealistSpinBox)
        self.verticalLayout_16.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_22 = QtWidgets.QLabel(self.frame_19)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.egotistSpinBox = QtWidgets.QSpinBox(self.frame_19)
        self.egotistSpinBox.setObjectName("egotistSpinBox")
        self.horizontalLayout_12.addWidget(self.egotistSpinBox)
        self.verticalLayout_16.addWidget(self.frame_19)
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.frame_18)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.susceptibleSpinBox = QtWidgets.QSpinBox(self.frame_18)
        self.susceptibleSpinBox.setObjectName("susceptibleSpinBox")
        self.horizontalLayout_11.addWidget(self.susceptibleSpinBox)
        self.verticalLayout_16.addWidget(self.frame_18)
        self.frame_20 = QtWidgets.QFrame(self.frame_13)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_20)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.idealistNSpinBox = QtWidgets.QSpinBox(self.frame_20)
        self.idealistNSpinBox.setObjectName("idealistNSpinBox")
        self.horizontalLayout_13.addWidget(self.idealistNSpinBox)
        self.verticalLayout_16.addWidget(self.frame_20)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.frame_17)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.egotistNSpinBox = QtWidgets.QSpinBox(self.frame_17)
        self.egotistNSpinBox.setObjectName("egotistNSpinBox")
        self.horizontalLayout_10.addWidget(self.egotistNSpinBox)
        self.verticalLayout_16.addWidget(self.frame_17)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.frame_15)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.susceptibleNSpinBox = QtWidgets.QSpinBox(self.frame_15)
        self.susceptibleNSpinBox.setObjectName("susceptibleNSpinBox")
        self.horizontalLayout_8.addWidget(self.susceptibleNSpinBox)
        self.verticalLayout_16.addWidget(self.frame_15)
        self.horizontalLayout_16.addWidget(self.frame_13)
        self.frame_23 = QtWidgets.QFrame(self.frame_8)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, round(70*heightSF)))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.numAgentsLabel = QtWidgets.QLabel(self.frame_23)
        self.numAgentsLabel.setMaximumSize(QtCore.QSize(16777215, round(50*heightSF)))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.numAgentsLabel.setFont(font)
        self.numAgentsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numAgentsLabel.setObjectName("numAgentsLabel")
        self.verticalLayout_17.addWidget(self.numAgentsLabel)
        self.simulationPlotWidget = MplWidget(self.frame_23)
        self.simulationPlotWidget.setObjectName("simulationPlotWidget")
        self.verticalLayout_17.addWidget(self.simulationPlotWidget)
        self.horizontalLayout_16.addWidget(self.frame_23)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_12 = QtWidgets.QFrame(self.simulationTab)
        self.frame_12.setMaximumSize(QtCore.QSize(round(200*widthSF), 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.loadProfilePushButton = QtWidgets.QPushButton(self.frame_12)
        self.loadProfilePushButton.setObjectName("loadProfilePushButton")
        self.verticalLayout_7.addWidget(self.loadProfilePushButton)
        self.saveProfilePushButton = QtWidgets.QPushButton(self.frame_12)
        self.saveProfilePushButton.setObjectName("saveProfilePushButton")
        self.verticalLayout_7.addWidget(self.saveProfilePushButton)
        self.runSimulationPushButton = QtWidgets.QPushButton(self.frame_12)
        self.runSimulationPushButton.setEnabled(False)
        self.runSimulationPushButton.setMinimumSize(QtCore.QSize(0, round(200*heightSF)))
        self.simStatusLabel = QtWidgets.QLabel(self.frame_12)
        self.simStatusLabel.setMaximumSize(QtCore.QSize(16777215, round(70*heightSF)))
        self.simStatusLabel.setFont(font)
        self.simStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.simStatusLabel.setObjectName("simStatusLabel")

        font = QtGui.QFont()
        font.setPointSize(20)
        self.runSimulationPushButton.setFont(font)
        self.runSimulationPushButton.setObjectName("runSimulationPushButton")
        self.verticalLayout_7.addWidget(self.runSimulationPushButton)
        self.verticalLayout_7.addWidget(self.simStatusLabel)
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.tabWidget_2.addTab(self.simulationTab, "")
        self.standardPlotsTab = QtWidgets.QWidget()
        self.standardPlotsTab.setObjectName("standardPlotsTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.standardPlotsTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.standardPlotWidget = MplWidget(self.standardPlotsTab)
        self.standardPlotWidget.setObjectName("standardPlotWidget")
        self.horizontalLayout_5.addWidget(self.standardPlotWidget)
        self.frame_2 = QtWidgets.QFrame(self.standardPlotsTab)
        self.frame_2.setMinimumSize(QtCore.QSize(round(200*widthSF), 0))
        self.frame_2.setMaximumSize(QtCore.QSize(round(200*widthSF), 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.selectCsvComboBox = QtWidgets.QComboBox(self.frame_2)
        self.selectCsvComboBox.setEnabled(False)
        self.selectCsvComboBox.setObjectName("selectCsvComboBox")
        self.verticalLayout_15.addWidget(self.selectCsvComboBox)
        self.standardPlotComboBox = QtWidgets.QComboBox(self.frame_2)
        self.standardPlotComboBox.setEnabled(False)
        self.standardPlotComboBox.setObjectName("standardPlotComboBox")
        self.verticalLayout_15.addWidget(self.standardPlotComboBox)
        self.saveCsvPushButton = QtWidgets.QPushButton(self.frame_2)
        self.saveCsvPushButton.setEnabled(False)
        self.saveCsvPushButton.setObjectName("saveCsvPushButton")
        self.verticalLayout_15.addWidget(self.saveCsvPushButton)
        self.saveAllPushButton = QtWidgets.QPushButton(self.frame_2)
        self.saveAllPushButton.setEnabled(False)
        self.saveAllPushButton.setObjectName("saveAllPushButton")
        self.verticalLayout_15.addWidget(self.saveAllPushButton)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.tabWidget_2.addTab(self.standardPlotsTab, "")
        self.customPlotTab = QtWidgets.QWidget()
        self.customPlotTab.setObjectName("customPlotTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.customPlotTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.customPlotTab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.customPlotWidget = MplWidget(self.frame_5)
        self.customPlotWidget.setObjectName("customPlotWidget")
        self.verticalLayout_5.addWidget(self.customPlotWidget)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, round(100*heightSF)))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minDay = QtWidgets.QLabel(self.frame_6)
        self.minDay.setObjectName("minDay")
        self.horizontalLayout_3.addWidget(self.minDay)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.maxDay = QtWidgets.QLabel(self.frame_6)
        self.maxDay.setObjectName("maxDay")
        self.horizontalLayout_3.addWidget(self.maxDay)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(round(60*widthSF), 0))
        self.frame_7.setMaximumSize(QtCore.QSize(round(80*widthSF), 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dayLabel = QtWidgets.QLabel(self.frame_7)
        self.dayLabel.setObjectName("dayLabel")
        self.verticalLayout_6.addWidget(self.dayLabel)
        self.dayPlotSpinBox = QtWidgets.QSpinBox(self.frame_7)
        self.dayPlotSpinBox.setEnabled(False)
        self.dayPlotSpinBox.setObjectName("dayPlotSpinBox")
        self.verticalLayout_6.addWidget(self.dayPlotSpinBox)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.customPlotTab)
        self.frame_3.setMinimumSize(QtCore.QSize(round(200*widthSF), 0))
        self.frame_3.setMaximumSize(QtCore.QSize(round(200*widthSF), 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setObjectName("tabWidget")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.plotTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gifButton = QtWidgets.QPushButton(self.plotTab)
        self.gifButton.setEnabled(False)
        self.gifButton.setObjectName("gifButton")
        self.verticalLayout_10.addWidget(self.gifButton)
        self.plotTypeGroup = QtWidgets.QGroupBox(self.plotTab)
        self.plotTypeGroup.setObjectName("plotTypeGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plotTypeGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plotTypeComboBox = QtWidgets.QComboBox(self.plotTypeGroup)
        self.plotTypeComboBox.setEnabled(False)
        self.plotTypeComboBox.setObjectName("plotTypeComboBox")
        self.verticalLayout_8.addWidget(self.plotTypeComboBox)
        self.label_11 = QtWidgets.QLabel(self.plotTypeGroup)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.agentComboBox = QtWidgets.QComboBox(self.plotTypeGroup)
        self.agentComboBox.setEnabled(False)
        self.agentComboBox.setObjectName("agentComboBox")
        self.verticalLayout_8.addWidget(self.agentComboBox)
        self.addAgentPushButton = QtWidgets.QPushButton(self.plotTypeGroup)
        self.addAgentPushButton.setEnabled(False)
        self.addAgentPushButton.setObjectName("addAgentPushButton")
        self.verticalLayout_8.addWidget(self.addAgentPushButton)
        self.clearAgentsPushButton = QtWidgets.QPushButton(self.plotTypeGroup)
        self.clearAgentsPushButton.setEnabled(False)
        self.clearAgentsPushButton.setObjectName("clearAgentsPushButton")
        self.verticalLayout_8.addWidget(self.clearAgentsPushButton)
        self.label_7 = QtWidgets.QLabel(self.plotTypeGroup)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.colourComboBox = QtWidgets.QComboBox(self.plotTypeGroup)
        self.colourComboBox.setEnabled(False)
        self.colourComboBox.setObjectName("colourComboBox")
        self.verticalLayout_8.addWidget(self.colourComboBox)
        self.averageBox = QtWidgets.QGroupBox(self.plotTypeGroup)
        self.averageBox.setMinimumSize(QtCore.QSize(0, round(100*heightSF)))
        self.averageBox.setObjectName("averageBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.averageBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.noneRadio = QtWidgets.QRadioButton(self.averageBox)
        self.noneRadio.setEnabled(False)
        self.noneRadio.setChecked(True)
        self.noneRadio.setObjectName("noneRadio")
        self.verticalLayout_9.addWidget(self.noneRadio)
        self.agentAverageRadio = QtWidgets.QRadioButton(self.averageBox)
        self.agentAverageRadio.setEnabled(False)
        self.agentAverageRadio.setObjectName("agentAverageRadio")
        self.verticalLayout_9.addWidget(self.agentAverageRadio)
        self.timeAverageRadio = QtWidgets.QRadioButton(self.averageBox)
        self.timeAverageRadio.setEnabled(False)
        self.timeAverageRadio.setObjectName("timeAverageRadio")
        self.verticalLayout_9.addWidget(self.timeAverageRadio)
        self.verticalLayout_8.addWidget(self.averageBox)
        self.verticalLayout_10.addWidget(self.plotTypeGroup)
        self.axesGroup = QtWidgets.QGroupBox(self.plotTab)
        self.axesGroup.setObjectName("axesGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.axesGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.axesGroup)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, round(20*heightSF)))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.xComboBox = QtWidgets.QComboBox(self.axesGroup)
        self.xComboBox.setEnabled(False)
        self.xComboBox.setObjectName("xComboBox")
        self.verticalLayout_4.addWidget(self.xComboBox)
        self.label_3 = QtWidgets.QLabel(self.axesGroup)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, round(20*heightSF)))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.yComboBox = QtWidgets.QComboBox(self.axesGroup)
        self.yComboBox.setEnabled(False)
        self.yComboBox.setObjectName("yComboBox")
        self.verticalLayout_4.addWidget(self.yComboBox)
        self.verticalLayout_10.addWidget(self.axesGroup)
        self.tabWidget.addTab(self.plotTab, "")
        self.filtersTab = QtWidgets.QWidget()
        self.filtersTab.setObjectName("filtersTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.filtersTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.filtersTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.filtersTab)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_11.addWidget(self.comboBox)
        self.label_5 = QtWidgets.QLabel(self.filtersTab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.frame_9 = QtWidgets.QFrame(self.filtersTab)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filterNumSpinBox = QtWidgets.QSpinBox(self.frame_10)
        self.filterNumSpinBox.setEnabled(False)
        self.filterNumSpinBox.setObjectName("filterNumSpinBox")
        self.horizontalLayout_4.addWidget(self.filterNumSpinBox)
        self.filterComboBox = QtWidgets.QComboBox(self.frame_10)
        self.filterComboBox.setEnabled(False)
        self.filterComboBox.setObjectName("filterComboBox")
        self.horizontalLayout_4.addWidget(self.filterComboBox)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.withRadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.withRadioButton.setChecked(True)
        self.withRadioButton.setObjectName("withRadioButton")
        self.verticalLayout_13.addWidget(self.withRadioButton)
        self.withoutRadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.withoutRadioButton.setObjectName("withoutRadioButton")
        self.verticalLayout_13.addWidget(self.withoutRadioButton)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.addFilterPushButton = QtWidgets.QPushButton(self.filtersTab)
        self.addFilterPushButton.setObjectName("addFilterPushButton")
        self.verticalLayout_11.addWidget(self.addFilterPushButton)
        self.clearFiltersPushButton = QtWidgets.QPushButton(self.filtersTab)
        self.clearFiltersPushButton.setObjectName("clearFiltersPushButton")
        self.verticalLayout_11.addWidget(self.clearFiltersPushButton)
        self.label_6 = QtWidgets.QLabel(self.filtersTab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.filterBrowser = QtWidgets.QTextBrowser(self.filtersTab)
        self.filterBrowser.setObjectName("filterBrowser")
        self.verticalLayout_11.addWidget(self.filterBrowser)
        self.tabWidget.addTab(self.filtersTab, "")
        self.statsTab = QtWidgets.QWidget()
        self.statsTab.setObjectName("statsTab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.statsTab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.statsTab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.statsTab)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.statsTab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.statsTab)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.label_8 = QtWidgets.QLabel(self.statsTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.statsTab)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.statsTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.ruleBrowser = QtWidgets.QTextBrowser(self.statsTab)
        self.ruleBrowser.setObjectName("ruleBrowser")
        self.verticalLayout_14.addWidget(self.ruleBrowser)
        self.tabWidget.addTab(self.statsTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_3)
        self.tabWidget_2.addTab(self.customPlotTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.loadCsvPushButton.clicked.connect(self.loadCsvSlot)
        self.lineEdit.returnPressed.connect(self.returnPressedSlot)
        self.addAgentPushButton.clicked.connect(self.addAgentSlot)
        self.noneRadio.clicked.connect(self.noneAverageSelected)
        self.dayPlotSpinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.gifButton.clicked.connect(self.exportGifSlot)
        self.horizontalSlider.valueChanged['int'].connect(self.dayPlotSpinBox.setValue)
        self.agentAverageRadio.clicked.connect(self.agentAverageSelected)
        self.timeAverageRadio.clicked.connect(self.timeAverageSelected)
        self.plotTypeComboBox.activated['QString'].connect(self.plotTypeSlot)
        self.xComboBox.activated['QString'].connect(self.xAxisSlot)
        self.yComboBox.activated['QString'].connect(self.yAxisSlot)
        self.addFilterPushButton.clicked.connect(self.addFilterSlot)
        self.clearFiltersPushButton.clicked.connect(self.removeAllFiltersSlot)
        self.comboBox.activated['QString'].connect(self.filterParameterSelectedSlot)
        self.colourComboBox.activated['QString'].connect(self.plotColourSlot)
        self.horizontalSlider.valueChanged['int'].connect(self.dayChangedSlot)
        self.saveAllPushButton.clicked.connect(self.saveAllSlot)
        self.saveCsvPushButton.clicked.connect(self.saveCsvSlot)
        self.standardPlotComboBox.activated['QString'].connect(self.standardPlotSelectSlot)
        self.selectCsvComboBox.activated['int'].connect(self.csvSelectSlot)
        self.loadProfilePushButton.clicked.connect(self.loadProfileSlot)
        self.saveProfilePushButton.clicked.connect(self.saveProfileSlot)
        self.runSimulationPushButton.clicked.connect(self.runSimulationSlot)
        self.balancedSpinBox.valueChanged['int'].connect(self.balancedUpdateSlot)
        self.idealistSpinBox.valueChanged['int'].connect(self.idealistUpdateSlot)
        self.egotistSpinBox.valueChanged['int'].connect(self.egotistUpdateSlot)
        self.susceptibleSpinBox.valueChanged['int'].connect(self.susceptibleUpdateSlot)
        self.idealistNSpinBox.valueChanged['int'].connect(self.idealistNUpdateSlot)
        self.egotistNSpinBox.valueChanged['int'].connect(self.egotistNUpdateSlot)
        self.susceptibleNSpinBox.valueChanged['int'].connect(self.susceptibleNUpdateSlot)
        self.daySpinBox.valueChanged['int'].connect(self.simDayUpdateSlot)
        self.runSpinBox.valueChanged['int'].connect(self.simRunUpdateSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOMAS"))
        self.label.setText(_translate("MainWindow", "File Name"))
        self.loadCsvPushButton.setText(_translate("MainWindow", "Load CSV..."))
        self.label_17.setText(_translate("MainWindow", "Simulation Runs"))
        self.label_25.setText(_translate("MainWindow", "Day Limit\n"
"(-1 for until\n"
"agents are dead)"))
        self.label_24.setText(_translate("MainWindow", "Balanced"))
        self.label_19.setText(_translate("MainWindow", "Idealist"))
        self.label_22.setText(_translate("MainWindow", "Egotist"))
        self.label_21.setText(_translate("MainWindow", "Susceptible"))
        self.label_23.setText(_translate("MainWindow", "Not Idealist"))
        self.label_20.setText(_translate("MainWindow", "Not Egotist"))
        self.label_18.setText(_translate("MainWindow", "Not Susceptible"))
        self.label_16.setText(_translate("MainWindow", "Number of Agents"))
        self.numAgentsLabel.setText(_translate("MainWindow", "0"))
        self.simStatusLabel.setText(_translate("MainWindow", "Waiting"))
        self.loadProfilePushButton.setText(_translate("MainWindow", "Load Setup..."))
        self.saveProfilePushButton.setText(_translate("MainWindow", "Save Setup..."))
        self.runSimulationPushButton.setText(_translate("MainWindow", "Run\n"
"Simulation"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.simulationTab), _translate("MainWindow", "Simulation"))
        self.saveCsvPushButton.setText(_translate("MainWindow", "Save Current CSV..."))
        self.saveAllPushButton.setText(_translate("MainWindow", "Save All Figures..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.standardPlotsTab), _translate("MainWindow", "Standard Plots"))
        self.minDay.setText(_translate("MainWindow", "0"))
        self.maxDay.setText(_translate("MainWindow", "0"))
        self.dayLabel.setText(_translate("MainWindow", "DAY"))
        self.gifButton.setText(_translate("MainWindow", "Export GIF"))
        self.plotTypeGroup.setTitle(_translate("MainWindow", "Plot Type"))
        self.label_11.setText(_translate("MainWindow", "Select agent"))
        self.addAgentPushButton.setText(_translate("MainWindow", "Add agent to plot"))
        self.clearAgentsPushButton.setText(_translate("MainWindow", "Clear all agents"))
        self.label_7.setText(_translate("MainWindow", "Colour by..."))
        self.averageBox.setTitle(_translate("MainWindow", "Average"))
        self.noneRadio.setText(_translate("MainWindow", "None"))
        self.agentAverageRadio.setText(_translate("MainWindow", "Agent Average"))
        self.timeAverageRadio.setText(_translate("MainWindow", "Time Average"))
        self.axesGroup.setTitle(_translate("MainWindow", "Axes"))
        self.label_2.setText(_translate("MainWindow", "x parameter"))
        self.label_3.setText(_translate("MainWindow", "y parameter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), _translate("MainWindow", "Plot"))
        self.label_4.setText(_translate("MainWindow", "Parameter"))
        self.label_5.setText(_translate("MainWindow", "Filter by"))
        self.withRadioButton.setText(_translate("MainWindow", "With"))
        self.withoutRadioButton.setText(_translate("MainWindow", "Without"))
        self.addFilterPushButton.setText(_translate("MainWindow", "Add filter"))
        self.clearFiltersPushButton.setText(_translate("MainWindow", "Clear all filters"))
        self.label_6.setText(_translate("MainWindow", "Active filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filtersTab), _translate("MainWindow", "Filters"))
        self.label_12.setText(_translate("MainWindow", "Duma chair"))
        self.label_13.setText(_translate("MainWindow", "N/A"))
        self.label_14.setText(_translate("MainWindow", "Number of dead agents"))
        self.label_15.setText(_translate("MainWindow", "N/A"))
        self.label_8.setText(_translate("MainWindow", "Mean/mode"))
        self.label_9.setText(_translate("MainWindow", "N/A"))
        self.label_10.setText(_translate("MainWindow", "Current ruleset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statsTab), _translate("MainWindow", "Stats"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.customPlotTab), _translate("MainWindow", "Custom Plot"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
